import Alert from "@mui/material/Alert";
import Chip from "@mui/material/Chip";
import Paper from "@mui/material/Paper";
import { ArrowLeft, Mail, Phone } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { InquiryAdminActions } from "../../../../../components/admin/inquiry-admin-actions";
import { ConfirmSubmitButton } from "../../../../../components/admin/confirm-submit-button";
import { Button } from "@daegwang/web-ui/components/ui/button";
import { deleteInquiryAction } from "../../../../../features/inquiries/actions";
import { getAdminInquiry } from "@daegwang/server/features/inquiries/queries";
import { inquiryStatusLabels, inquiryTypeLabels } from "@daegwang/contracts/features/inquiries/schema";
import { requireSuperAdmin } from "../../../../../lib/auth/permissions";
const date = (value: Date) => new Intl.DateTimeFormat("ko-KR", { dateStyle: "long", timeStyle: "short" }).format(value);
export default async function InquiryDetailPage({ params }: { params: Promise<{ id: string }> }) { await requireSuperAdmin(); const { id } = await params; const inquiry = await getAdminInquiry(id); if (!inquiry) notFound(); return <div className="mx-auto max-w-[90rem]"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/admin/inquiries" className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-primary-700"><ArrowLeft className="size-4" /> 문의 목록</Link><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-extrabold tracking-[-0.04em]">{inquiry.title || `${inquiryTypeLabels[inquiry.type]} 문의`}</h1><Chip label={inquiryStatusLabels[inquiry.status]} color={inquiry.status === "NEW" ? "error" : inquiry.status === "COMPLETED" ? "success" : "default"} /></div><p className="mt-2 text-text-secondary">{date(inquiry.createdAt)} 접수 · 개인정보 동의 {date(inquiry.privacyAgreedAt)}</p></div><form action={deleteInquiryAction.bind(null, id)}><ConfirmSubmitButton message="문의 내용과 내부 메모를 영구 삭제합니다. 이 작업은 되돌릴 수 없습니다. 계속하시겠습니까?" label="영구 삭제" /></form></div><Alert severity="warning" className="mt-6!">문의 내용과 연락처를 외부에 공유하지 말고, 처리 목적이 끝난 정보는 삭제해 주세요.</Alert><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_22rem]"><div className="grid gap-6"><Paper variant="outlined" className="p-6 md:p-8"><div className="grid gap-5 sm:grid-cols-2"><Info label="문의 유형" value={inquiryTypeLabels[inquiry.type]} /><Info label="이름" value={inquiry.name} /><Info label="선호 연락" value={inquiry.preferredContact || "지정 안 함"} /><Info label="처리 상태" value={inquiryStatusLabels[inquiry.status]} /></div><div className="mt-6 flex flex-wrap gap-3">{inquiry.phone ? <Button asChild variant="secondary"><a href={`tel:${inquiry.phone}`}><Phone className="size-4" /> {inquiry.phone}</a></Button> : null}{inquiry.email ? <Button asChild variant="secondary"><a href={`mailto:${inquiry.email}`}><Mail className="size-4" /> {inquiry.email}</a></Button> : null}</div><div className="mt-8 border-t border-border pt-7"><h2 className="font-extrabold">문의 내용</h2><p className="mt-4 whitespace-pre-line leading-8 text-text-secondary">{inquiry.content}</p></div></Paper><section><h2 className="text-xl font-extrabold">내부 메모</h2>{inquiry.notes.length ? <div className="mt-4 grid gap-3">{inquiry.notes.map((note) => <Paper key={note.id} variant="outlined" className="p-5"><p className="whitespace-pre-line leading-7">{note.content}</p><p className="mt-3 text-xs text-text-secondary">{note.author.displayName} · {date(note.createdAt)}</p></Paper>)}</div> : <Paper variant="outlined" className="mt-4 p-6 text-text-secondary">등록된 내부 메모가 없습니다.</Paper>}</section></div><InquiryAdminActions id={id} status={inquiry.status} /></div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-sm font-bold text-text-secondary">{label}</dt><dd className="mt-1 font-extrabold">{value}</dd></div>; }
