"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { parseAdminProfile } from "@/features/admins/schema";
import { requireSuperAdmin } from "@/lib/auth/permissions";
import { getPrisma } from "@/lib/db/prisma";
export type AdminProfileActionState = { message?: string; errors?: Record<string, string[]> };
function refresh() { revalidatePath("/admin/admins"); revalidatePath("/admin/activity"); }
export async function createAdminProfileAction(_state: AdminProfileActionState, formData: FormData): Promise<AdminProfileActionState> { const actor = await requireSuperAdmin(); const result = parseAdminProfile(formData); if (!result.success) return { message: "입력값을 확인해 주세요.", errors: result.error.flatten().fieldErrors }; let id = ""; try { await getPrisma().$transaction(async (tx) => { const item = await tx.adminProfile.create({ data: result.data }); id = item.id; await tx.activityLog.create({ data: { actorId: actor.id, action: "CREATE", entityType: "AdminProfile", entityId: item.id, summary: `관리자 '${item.displayName}' 연결` } }); }); } catch (error) { console.error(error); return { message: "관리자를 등록하지 못했습니다. UUID 또는 이메일이 이미 등록되었는지 확인해 주세요." }; } refresh(); redirect(`/admin/admins/${id}/edit`); }
export async function updateAdminProfileAction(id: string, _state: AdminProfileActionState, formData: FormData): Promise<AdminProfileActionState> { const actor = await requireSuperAdmin(); const result = parseAdminProfile(formData); if (!result.success) return { message: "입력값을 확인해 주세요.", errors: result.error.flatten().fieldErrors }; if (id === actor.id && (!result.data.isActive || result.data.role !== "SUPER_ADMIN")) return { message: "현재 로그인한 최고 관리자 자신의 권한이나 활성 상태는 변경할 수 없습니다." }; try { await getPrisma().$transaction(async (tx) => { const item = await tx.adminProfile.update({ where: { id }, data: result.data }); await tx.activityLog.create({ data: { actorId: actor.id, action: "UPDATE", entityType: "AdminProfile", entityId: item.id, summary: `관리자 '${item.displayName}' 정보 수정` } }); }); } catch (error) { console.error(error); return { message: "관리자 정보를 수정하지 못했습니다." }; } refresh(); redirect(`/admin/admins/${id}/edit`); }
