import { getPrisma } from '@daegwang/database/prisma';
import { requireAdmin } from '../../../../lib/auth/permissions';
import { OperationForm } from '../../../../components/admin/operation-form';
import { saveGroupAction, saveGroupNoticeAction, saveMembershipAction, saveGroupManagerAction } from './actions';
export default async function GroupsPage() {
  const admin = await requireAdmin(); const db = getPrisma(); const superAdmin = admin.role === 'SUPER_ADMIN';
  const groups = await db.churchGroup.findMany({ where: superAdmin ? {} : { managers: { some: { adminId: admin.id } } }, orderBy: { name: 'asc' }, include: { managers: true, _count: { select: { memberships: true } } } });
  const notices = await db.groupNotice.findMany({ where: { groupId: { in: groups.map(g => g.id) }, deletedAt: null }, orderBy: { updatedAt: 'desc' }, take: 100 });
  const profiles = superAdmin ? await db.memberProfile.findMany({ select: { ownerId: true, displayName: true }, orderBy: { displayName: 'asc' }, take: 200 }) : [];
  const admins = superAdmin ? await db.adminProfile.findMany({ where: { isActive: true }, select: { id: true, displayName: true } }) : [];
  const memberships = superAdmin ? await db.groupMembership.findMany({ where: { groupId: { in: groups.map(g => g.id) } }, select: { ownerId: true, groupId: true } }) : [];
  const groupOptions = groups.filter(g => g.isActive).map(g => <option key={g.id} value={g.id}>{g.name}</option>);
  return <div className="mx-auto max-w-5xl space-y-7">
    <header><h1 className="text-3xl font-extrabold">모임·소속 소식</h1><p className="mt-3 text-text-secondary">관심 모임은 소식을 모아보는 선택입니다. 소속 전용 안내는 별도 승인된 회원만 읽습니다.</p></header>
    {process.env.APP_GROUPS_ENABLED !== 'true' && <p role="status" className="rounded-xl bg-primary-50 p-4">앱 공개는 아직 꺼져 있습니다. 실제 모임과 담당자를 정한 뒤 시작하세요.</p>}
    {!groups.length && <p className="rounded-2xl border border-border bg-white p-6">등록된 모임이 없습니다. 예시 모임을 실제 모임으로 자동 등록하지 않습니다.</p>}
    {groups.map(g => <section key={g.id} className="rounded-2xl border border-border bg-white p-5"><h2 className="text-xl font-bold">{g.name}</h2><p className="mt-2">{g.description}</p><p className="mt-2 text-sm text-text-secondary">{g.isActive ? '활성' : '비활성'} · 승인된 소속 {g._count.memberships}명 · 담당자 {g.managers.length}명</p>{superAdmin && <p className="mt-2 text-sm">소속: {memberships.filter(m => m.groupId === g.id).map(m => profiles.find(p => p.ownerId === m.ownerId)?.displayName || `회원 ${m.ownerId.slice(0, 8)}`).join(', ') || '없음'}</p>}</section>)}
    {superAdmin && <OperationForm action={saveGroupAction} submit="모임 등록"><h2 className="text-xl font-bold">새 모임 등록</h2><GroupFields /></OperationForm>}
    {superAdmin && groups.map(g => <OperationForm key={g.id} action={saveGroupAction} submit="모임 수정 저장"><h2 className="text-xl font-bold">{g.name} 수정</h2><input type="hidden" name="id" value={g.id} /><input type="hidden" name="version" value={g.version} /><GroupFields group={g} /></OperationForm>)}
    {superAdmin && groupOptions.length > 0 && <div className="grid gap-5 md:grid-cols-2"><OperationForm action={saveMembershipAction} submit="소속 변경"><h2 className="text-xl font-bold">소속 승인·해제</h2><label className="block">모임<select name="groupId">{groupOptions}</select></label><label className="block">회원<select name="ownerId" required><option value="">회원을 선택하세요</option>{profiles.map(p => <option key={p.ownerId} value={p.ownerId}>{p.displayName || '이름 미입력'} · {p.ownerId.slice(0, 8)}</option>)}</select></label><label className="block">처리<select name="approved"><option value="true">소속 승인</option><option value="false">소속 해제</option></select></label><p className="text-sm">회원이 앱의 계정관리 화면을 이용한 뒤 목록에 나타납니다. 개인 묵상·기도는 조회하지 않습니다.</p></OperationForm><OperationForm action={saveGroupManagerAction} submit="담당자 변경"><h2 className="text-xl font-bold">모임 담당자 지정</h2><label className="block">모임<select name="groupId">{groupOptions}</select></label><label className="block">관리자<select name="adminId">{admins.map(a => <option key={a.id} value={a.id}>{a.displayName}</option>)}</select></label><label className="block">권한<select name="assigned"><option value="true">담당자 지정</option><option value="false">담당자 해제</option></select></label></OperationForm></div>}
    {groupOptions.length > 0 && <OperationForm action={saveGroupNoticeAction} submit="새 공지 저장"><h2 className="text-xl font-bold">모임 공지 등록</h2><label className="block">모임<select name="groupId">{groupOptions}</select></label><NoticeFields /></OperationForm>}
    {notices.map(n => <OperationForm key={`${n.id}-${n.version}`} action={saveGroupNoticeAction} submit="공지 수정 저장"><h2 className="text-lg font-bold">{n.title}</h2><input type="hidden" name="id" value={n.id} /><input type="hidden" name="version" value={n.version} /><input type="hidden" name="groupId" value={n.groupId} /><NoticeFields notice={n} /></OperationForm>)}
  </div>;
}
function NoticeFields({ notice }: { notice?: { title: string; body: string; audience: string; status: string } }) { return <><label className="block">제목<input name="title" required maxLength={200} defaultValue={notice?.title} /></label><label className="block">본문<textarea name="body" required rows={5} maxLength={20000} defaultValue={notice?.body} /></label><label className="block">열람 대상<select name="audience" defaultValue={notice?.audience ?? 'MEMBERS'}><option value="MEMBERS">승인된 소속만</option><option value="PUBLIC">누구나</option></select></label><label className="block">공개 상태<select name="status" defaultValue={notice?.status ?? 'DRAFT'}><option value="DRAFT">임시저장</option><option value="PUBLISHED">게시</option><option value="PRIVATE">비공개</option></select></label><p className="text-sm text-text-secondary">모임 공지는 앱의 모임 소식에서 제공합니다. 소속 전용 공지는 공개 홈페이지에 보내지 않으며 첨부파일·푸시 발송은 아직 지원하지 않습니다.</p></>; }

function GroupFields({group}: {group?: {name: string; description: string; isActive: boolean}}) {return <><label className="block">모임 이름<input name="name" required maxLength={80} defaultValue={group?.name} /></label><label className="block">소개<textarea name="description" rows={3} maxLength={1000} defaultValue={group?.description} /></label><label className="flex items-center gap-2"><input className="!w-5" type="checkbox" name="isActive" defaultChecked={group?.isActive ?? true} />활성 모임</label></>; }
