"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { parseScheduleFormData } from "@/features/schedules/schema";
import { requireAdmin } from "@/lib/auth/permissions";
import { getPrisma } from "@/lib/db/prisma";
export type ScheduleActionState = { message?: string; errors?: Record<string, string[]> };
function paths() { revalidatePath("/admin/pages/worship-info"); revalidatePath("/about/worship-info"); }
function parse(formData: FormData): { ok: true; data: ReturnType<typeof parseScheduleFormData>["data"] & object } | { ok: false; state: ScheduleActionState } { const result = parseScheduleFormData(formData); return result.success ? { ok: true, data: result.data } : { ok: false, state: { message: "입력값을 확인해 주세요.", errors: result.error.flatten().fieldErrors } }; }
export async function createScheduleAction(_state: ScheduleActionState, formData: FormData): Promise<ScheduleActionState> { const admin = await requireAdmin(); const parsed = parse(formData); if (!parsed.ok) return parsed.state; let id = ""; try { await getPrisma().$transaction(async (tx) => { const item = await tx.worshipSchedule.create({ data: parsed.data }); id = item.id; await tx.activityLog.create({ data: { actorId: admin.id, action: "CREATE", entityType: "WorshipSchedule", entityId: item.id, summary: `예배시간 '${item.name}' 등록` } }); }); } catch (error) { console.error(error); return { message: "예배시간을 저장하지 못했습니다." }; } paths(); redirect(`/admin/pages/worship-info/${id}/edit`); }
export async function updateScheduleAction(id: string, _state: ScheduleActionState, formData: FormData): Promise<ScheduleActionState> { const admin = await requireAdmin(); const parsed = parse(formData); if (!parsed.ok) return parsed.state; try { await getPrisma().$transaction(async (tx) => { const item = await tx.worshipSchedule.update({ where: { id }, data: parsed.data }); await tx.activityLog.create({ data: { actorId: admin.id, action: "UPDATE", entityType: "WorshipSchedule", entityId: item.id, summary: `예배시간 '${item.name}' 수정` } }); }); } catch (error) { console.error(error); return { message: "예배시간을 수정하지 못했습니다." }; } paths(); redirect(`/admin/pages/worship-info/${id}/edit`); }
export async function deleteScheduleAction(id: string) { const admin = await requireAdmin(); await getPrisma().$transaction(async (tx) => { const item = await tx.worshipSchedule.update({ where: { id }, data: { deletedAt: new Date() } }); await tx.activityLog.create({ data: { actorId: admin.id, action: "DELETE", entityType: "WorshipSchedule", entityId: item.id, summary: `예배시간 '${item.name}' 삭제` } }); }); paths(); redirect("/admin/pages/worship-info"); }
