"use server";
import { revalidatePath } from "@/lib/revalidate";
import { redirect } from "next/navigation";
import { Prisma } from "@daegwang/database/generated/client";
import { parseMinistryFormData } from "@daegwang/contracts/features/ministries/schema";
import { requireAdmin } from "../../lib/auth/permissions";
import { getPrisma } from "@daegwang/database/prisma";
import { createClient } from "../../lib/supabase/server";

export type MinistryActionState = { message?: string; errors?: Record<string, string[]> };
const BUCKET = "public-assets"; const MAX_SIZE = 5 * 1024 * 1024; const allowed = new Map([["image/jpeg", "jpg"], ["image/png", "png"], ["image/webp", "webp"]]);
function file(formData: FormData) { const value = formData.get("coverImage"); return value instanceof File && value.size ? value : null; }
function validate(image: File | null) { if (!image) return null; if (!allowed.has(image.type)) return "JPG, PNG, WebP 이미지만 업로드할 수 있습니다."; if (image.size > MAX_SIZE) return "대표 이미지는 5MB 이하여야 합니다."; return null; }
function programs(value?: string) { return value ? value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean) : []; }
async function upload(image: File) { const path = `ministries/${crypto.randomUUID()}.${allowed.get(image.type)}`; const supabase = await createClient(); const { error } = await supabase.storage.from(BUCKET).upload(path, image, { contentType: image.type, cacheControl: "31536000" }); if (error) throw new Error(error.message); return path; }
async function remove(bucket: string, path: string) { const supabase = await createClient(); const { error } = await supabase.storage.from(bucket).remove([path]); if (error) console.error("Failed to remove ministry image", error); }
function refresh(slug?: string) { revalidatePath("/admin/ministries"); if (slug) revalidatePath(`/ministries/${slug}`); }
function data(input: ReturnType<typeof parseMinistryFormData>["data"] & object) { return { name: input.name, slug: input.slug, type: input.type, introduction: input.introduction, audience: input.audience ?? null, meetingDay: input.meetingDay ?? null, meetingTime: input.meetingTime ?? null, location: input.location ?? null, leader: input.leader ?? null, contactName: input.contactName ?? null, contactValue: input.contactValue ?? null, showContact: input.showContact, sections: input.programText ? { programs: programs(input.programText) } : Prisma.JsonNull, status: input.status, sortOrder: input.sortOrder }; }

export async function createMinistryAction(_state: MinistryActionState, formData: FormData): Promise<MinistryActionState> { const admin = await requireAdmin(); const parsed = parseMinistryFormData(formData); if (!parsed.success) return { message: "입력값을 확인해 주세요.", errors: parsed.error.flatten().fieldErrors }; const image = file(formData); const imageError = validate(image); if (imageError) return { message: imageError, errors: { coverImage: [imageError] } }; let path = "", id = ""; try { if (image) path = await upload(image); await getPrisma().$transaction(async (tx) => { let coverImageId: string | undefined; if (image && path) coverImageId = (await tx.media.create({ data: { bucket: BUCKET, objectPath: path, originalName: image.name, mimeType: image.type, sizeBytes: image.size, altText: `${parsed.data.name} 대표 이미지`, visibility: "PUBLIC" } })).id; const ministry = await tx.ministry.create({ data: { ...data(parsed.data), coverImageId, publishedAt: parsed.data.status === "PUBLISHED" ? new Date() : null } }); id = ministry.id; await tx.activityLog.create({ data: { actorId: admin.id, action: "CREATE", entityType: "Ministry", entityId: ministry.id, summary: `사역 '${ministry.name}' 등록` } }); }); } catch (error) { console.error(error); if (path) await remove(BUCKET, path); return { message: "사역을 저장하지 못했습니다. 같은 주소가 이미 사용 중인지 확인해 주세요." }; } refresh(parsed.data.slug); redirect(`/admin/ministries/${id}/edit`); }

export async function updateMinistryAction(id: string, _state: MinistryActionState, formData: FormData): Promise<MinistryActionState> { const admin = await requireAdmin(); const parsed = parseMinistryFormData(formData); if (!parsed.success) return { message: "입력값을 확인해 주세요.", errors: parsed.error.flatten().fieldErrors }; const image = file(formData); const imageError = validate(image); if (imageError) return { message: imageError, errors: { coverImage: [imageError] } }; const prisma = getPrisma(); const current = await prisma.ministry.findFirst({ where: { id, deletedAt: null }, include: { coverImage: true } }); if (!current) return { message: "사역을 찾지 못했습니다." }; let path = "", replace = false; try { if (image) path = await upload(image); await prisma.$transaction(async (tx) => { let coverImageId = current.coverImageId; if (image && path) { coverImageId = (await tx.media.create({ data: { bucket: BUCKET, objectPath: path, originalName: image.name, mimeType: image.type, sizeBytes: image.size, altText: `${parsed.data.name} 대표 이미지`, visibility: "PUBLIC" } })).id; replace = Boolean(current.coverImageId); } else if (parsed.data.removeCoverImage) { coverImageId = null; replace = Boolean(current.coverImageId); } const ministry = await tx.ministry.update({ where: { id }, data: { ...data(parsed.data), coverImageId, publishedAt: parsed.data.status === "PUBLISHED" ? current.publishedAt ?? new Date() : null } }); if (replace && current.coverImageId) await tx.media.update({ where: { id: current.coverImageId }, data: { deletedAt: new Date() } }); await tx.activityLog.create({ data: { actorId: admin.id, action: "UPDATE", entityType: "Ministry", entityId: ministry.id, summary: `사역 '${ministry.name}' 수정` } }); }); if (replace && current.coverImage) await remove(current.coverImage.bucket, current.coverImage.objectPath); } catch (error) { console.error(error); if (path) await remove(BUCKET, path); return { message: "사역을 수정하지 못했습니다. 같은 주소가 이미 사용 중인지 확인해 주세요." }; } refresh(current.slug); refresh(parsed.data.slug); redirect(`/admin/ministries/${id}/edit`); }

export async function deleteMinistryAction(id: string) { const admin = await requireAdmin(); let slug = ""; await getPrisma().$transaction(async (tx) => { const item = await tx.ministry.update({ where: { id }, data: { deletedAt: new Date() } }); slug = item.slug; await tx.activityLog.create({ data: { actorId: admin.id, action: "DELETE", entityType: "Ministry", entityId: item.id, summary: `사역 '${item.name}' 삭제` } }); }); refresh(slug); redirect("/admin/ministries"); }
