import "server-only";
import type { Prisma } from "@daegwang/database/generated/client";
import { cache } from "react";
import { getPrisma } from "@daegwang/database/prisma";
import { hasDatabaseConfig } from "@daegwang/config/env";
import { publicEnv } from "@daegwang/config/env";
export type PublicSiteSettings = { siteName: string; description: string; canonicalUrl: string; address: string; addressDetail: string; phone: string; email: string; mapLatitude?: number; mapLongitude?: number; youtubeUrl: string; transitInfo: string; parkingInfo: string; privacyOfficer: string; privacyContact: string };
export const defaultSiteSettings: PublicSiteSettings = { siteName: "대광교회", description: "예배를 통해 세상이 회복됨을 믿는 대한예수교장로회(고신) 대광교회입니다.", canonicalUrl: publicEnv.NEXT_PUBLIC_SITE_URL, address: "", addressDetail: "", phone: "", email: "", youtubeUrl: "https://www.youtube.com/@서울독산동대광교회", transitInfo: "", parkingInfo: "", privacyOfficer: "", privacyContact: "" };
function record(value: Prisma.JsonValue | null): Record<string, Prisma.JsonValue> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, Prisma.JsonValue> : {}; }
function value(data: Record<string, Prisma.JsonValue>, key: string) { return typeof data[key] === "string" ? data[key] as string : ""; }
export const getSiteSettings = cache(async (): Promise<PublicSiteSettings> => { if (!hasDatabaseConfig()) return defaultSiteSettings; try { const item = await getPrisma().siteSetting.findUnique({ where: { singletonKey: "SITE" } }); if (!item) return defaultSiteSettings; const contact = record(item.contactOptions); return { siteName: item.siteName, description: item.description || defaultSiteSettings.description, canonicalUrl: item.canonicalUrl, address: item.address || "", addressDetail: item.addressDetail || "", phone: item.phone || "", email: item.email || "", mapLatitude: item.mapLatitude ? Number(item.mapLatitude) : undefined, mapLongitude: item.mapLongitude ? Number(item.mapLongitude) : undefined, youtubeUrl: item.youtubeUrl || "", transitInfo: value(contact, "transitInfo"), parkingInfo: value(contact, "parkingInfo"), privacyOfficer: value(contact, "privacyOfficer"), privacyContact: value(contact, "privacyContact") }; } catch (error) { if ((error as { code?: string }).code !== "EACCES") console.error("Failed to load site settings", error); return defaultSiteSettings; } });
