"use client";
import Alert from "@mui/material/Alert";
import Checkbox from "@mui/material/Checkbox";
import FormControlLabel from "@mui/material/FormControlLabel";
import MenuItem from "@mui/material/MenuItem";
import Paper from "@mui/material/Paper";
import TextField from "@mui/material/TextField";
import { ImageIcon, LoaderCircle, Save } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useActionState, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { createMinistryAction, updateMinistryAction, type MinistryActionState } from "@/features/ministries/actions";
import { ministryStatusLabels, ministryTypeLabels } from "@/features/ministries/schema";

export type MinistryFormValues = { id?: string; name?: string; slug?: string; type?: keyof typeof ministryTypeLabels; introduction?: string; audience?: string; meetingDay?: string; meetingTime?: string; location?: string; leader?: string; contactName?: string; contactValue?: string; showContact?: boolean; programText?: string; status?: keyof typeof ministryStatusLabels; sortOrder?: number; coverImageUrl?: string };
export function MinistryForm({ initialValues = {} }: { initialValues?: MinistryFormValues }) { const action = useMemo(() => initialValues.id ? updateMinistryAction.bind(null, initialValues.id) : createMinistryAction, [initialValues.id]); const [state, formAction, pending] = useActionState(action, {} as MinistryActionState); const error = (name: string) => state.errors?.[name]?.[0]; return <form action={formAction} className="mt-8 grid gap-6 lg:grid-cols-[1fr_20rem]">
  <Paper variant="outlined" className="flex flex-col gap-6 p-5 md:p-7">{state.message ? <Alert severity="error">{state.message}</Alert> : null}
    <div className="grid gap-6 sm:grid-cols-2"><TextField required fullWidth label="사역명" name="name" defaultValue={initialValues.name ?? ""} error={Boolean(error("name"))} helperText={error("name")} /><TextField select required fullWidth label="사역 구분" name="type" defaultValue={initialValues.type ?? "OTHER"} error={Boolean(error("type"))} helperText={error("type")}>{Object.entries(ministryTypeLabels).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></div>
    <TextField required fullWidth label="페이지 주소" name="slug" defaultValue={initialValues.slug ?? ""} error={Boolean(error("slug"))} helperText={error("slug") ?? "예: elementary → /ministries/elementary"} />
    <TextField required fullWidth multiline minRows={8} label="사역 소개" name="introduction" defaultValue={initialValues.introduction ?? ""} error={Boolean(error("introduction"))} helperText={error("introduction")} />
    <div className="grid gap-6 sm:grid-cols-2"><TextField label="대상" name="audience" defaultValue={initialValues.audience ?? ""} error={Boolean(error("audience"))} helperText={error("audience")} /><TextField label="담당자" name="leader" defaultValue={initialValues.leader ?? ""} error={Boolean(error("leader"))} helperText={error("leader")} /><TextField label="모임 요일" name="meetingDay" defaultValue={initialValues.meetingDay ?? ""} error={Boolean(error("meetingDay"))} helperText={error("meetingDay") ?? "예: 매주 주일"} /><TextField label="모임 시간" name="meetingTime" defaultValue={initialValues.meetingTime ?? ""} error={Boolean(error("meetingTime"))} helperText={error("meetingTime") ?? "예: 오전 11:00"} /></div>
    <TextField fullWidth label="모임 장소" name="location" defaultValue={initialValues.location ?? ""} error={Boolean(error("location"))} helperText={error("location")} />
    <TextField fullWidth multiline minRows={5} label="프로그램·활동" name="programText" defaultValue={initialValues.programText ?? ""} error={Boolean(error("programText"))} helperText={error("programText") ?? "한 줄에 한 항목씩 입력하세요."} />
    <section className="grid gap-6 rounded-2xl bg-background-muted p-5 sm:grid-cols-2"><TextField label="문의 담당자" name="contactName" defaultValue={initialValues.contactName ?? ""} error={Boolean(error("contactName"))} helperText={error("contactName")} /><TextField label="문의 연락처" name="contactValue" defaultValue={initialValues.contactValue ?? ""} error={Boolean(error("contactValue"))} helperText={error("contactValue")} /><FormControlLabel control={<Checkbox name="showContact" defaultChecked={initialValues.showContact} />} label="공개 페이지에 문의 연락처 표시" /></section>
    <div className={`rounded-2xl border border-dashed p-6 ${error("coverImage") ? "border-red-500" : "border-border"}`}><div className="flex flex-col gap-5 sm:flex-row">{initialValues.coverImageUrl ? <Image src={initialValues.coverImageUrl} alt="현재 대표 이미지" width={240} height={180} className="aspect-[4/3] w-48 rounded-2xl object-cover" /> : <div className="flex aspect-[4/3] w-48 items-center justify-center rounded-2xl bg-white"><ImageIcon className="size-9 text-primary-600" /></div>}<div className="min-w-0 flex-1"><label htmlFor="coverImage" className="font-extrabold">대표 이미지 {initialValues.coverImageUrl ? "교체" : "업로드"}</label><p className="mt-1 text-sm text-text-secondary">JPG, PNG, WebP · 최대 5MB</p><input id="coverImage" name="coverImage" type="file" accept="image/jpeg,image/png,image/webp" className="mt-4 block w-full text-sm file:mr-4 file:rounded-full file:border-0 file:bg-primary-50 file:px-4 file:py-2 file:font-bold file:text-primary-700" />{error("coverImage") ? <p className="mt-2 text-sm text-red-600">{error("coverImage")}</p> : null}{initialValues.coverImageUrl ? <FormControlLabel className="mt-3!" control={<Checkbox name="removeCoverImage" />} label="대표 이미지 삭제" /> : null}</div></div></div>
  </Paper>
  <Paper component="aside" variant="outlined" className="flex h-fit flex-col gap-5 p-5 lg:sticky lg:top-24"><h2 className="font-extrabold">공개 설정</h2><TextField select fullWidth size="small" label="상태" name="status" defaultValue={initialValues.status ?? "DRAFT"}>{Object.entries(ministryStatusLabels).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField><TextField type="number" size="small" label="노출 순서" name="sortOrder" defaultValue={initialValues.sortOrder ?? 0} helperText="숫자가 작을수록 먼저 표시됩니다." /><Alert severity="info">공개 상태로 저장한 사역만 홈페이지에서 확인할 수 있습니다.</Alert><div className="grid gap-2 pt-2"><Button type="submit" disabled={pending}>{pending ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}{pending ? "업로드 및 저장 중" : "저장"}</Button><Button asChild variant="secondary"><Link href="/admin/ministries">취소</Link></Button></div></Paper>
</form>; }
