import type { Metadata } from "next";
import { CalendarDays, MapPin, UserRound } from "lucide-react";
import Link from "next/link";
import { ContentShell, SectionTitle } from "../../../../components/site/content-shell";
import { PageHero } from "../../../../components/site/page-hero";
import { Button } from "@daegwang/web-ui/components/ui/button";
import { getNewcomerEducationContent } from "@daegwang/server/features/pages/queries";
export const metadata: Metadata = { title: "새가족 교육", description: "대광교회 새가족의 정착과 성장을 위한 과정입니다.", alternates: { canonical: "/newcomer/education" } };
export const dynamic = "force-dynamic";
export default async function NewcomerEducationPage() { const { content } = await getNewcomerEducationContent(); return <><PageHero eyebrow="NEWCOMER JOURNEY" title={content.heroTitle} description={content.heroDescription} /><ContentShell><SectionTitle eyebrow="PROCESS" title={content.processTitle} /><ol className="mt-10">{content.steps.map((item, index) => <li key={`${index}-${item.title}`} className="grid gap-4 border-t border-border py-7 last:border-b md:grid-cols-[6rem_1fr] md:items-start"><span className="text-sm font-extrabold text-primary-700">STEP {index + 1}</span><div><h2 className="text-2xl font-extrabold tracking-[-0.03em]">{item.title}</h2><p className="mt-2 whitespace-pre-line leading-7 text-text-secondary">{item.description}</p></div></li>)}</ol><section className="mt-14 grid gap-4 md:grid-cols-3"><Info icon={CalendarDays} label="교육 기간" value={content.duration} /><Info icon={MapPin} label="교육 장소" value={content.location} /><Info icon={UserRound} label="담당" value={content.leader} /></section><aside className="mt-10 flex flex-col gap-5 rounded-2xl bg-primary-50 p-7 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-extrabold">신청 안내</h2><p className="mt-2 whitespace-pre-line leading-7 text-text-secondary">{content.applicationInfo}</p></div><Button asChild className="shrink-0"><Link href="/newcomer/register">새가족 등록 문의</Link></Button></aside></ContentShell></>; }
function Info({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { return <article className="rounded-2xl border border-border p-6"><Icon className="size-6 text-primary-600" /><p className="mt-5 text-sm font-bold text-text-secondary">{label}</p><p className="mt-2 whitespace-pre-line font-extrabold leading-7">{value}</p></article>; }
