import Link from 'next/link';
import type { AppReadiness } from '../../lib/app-readiness';
import { Button } from '@daegwang/web-ui/components/ui/button';
export function AppOperations({ channels, preview = false, checks = [] }: { channels: AppReadiness[]; preview?: boolean; checks?: { label: string; detail: string; href: string; ready: boolean }[] }) {
  return <div className="mx-auto max-w-6xl space-y-7">
    <div><p className="text-sm font-bold text-primary-700">홈페이지 · 앱 관리</p><h1 className="mt-2 text-3xl font-extrabold">앱 운영 현황</h1><p className="mt-3 text-text-secondary">교인이 필요한 말씀과 소식을 제때 찾을 수 있도록, 공개 채널과 다음 작업을 확인합니다.</p></div>
    {checks.length > 0 && <section aria-label="현재 연결과 운영 준비" className="rounded-2xl border border-border bg-white p-6"><h2 className="text-xl font-bold">현재 연결과 운영 준비</h2><p className="mt-2 text-sm text-text-secondary">현재 데이터와 설정을 기준으로 표시합니다. 개인 기록 내용이나 계정 비밀정보는 조회하지 않습니다.</p><ul className="mt-4 divide-y divide-border">{checks.map(check => <li key={check.label} className="flex flex-col gap-2 py-4 sm:flex-row sm:justify-between"><div><h3 className="font-bold">{check.label} · {check.ready ? '연결 확인' : '확인 필요'}</h3><p className="mt-1 text-sm text-text-secondary">{check.detail}</p></div><Link href={check.href} className="shrink-0 self-start rounded-lg border border-border px-3 py-2 text-sm font-bold text-primary-700">관리 화면</Link></li>)}</ul></section>}
    <section aria-labelledby="operation-priority" className="rounded-2xl border border-border bg-white p-6"><h2 id="operation-priority" className="text-xl font-bold">오늘 확인할 일</h2><ol className="mt-4 list-decimal space-y-3 pl-5"><li>오늘의 첫시간 주님께 날짜와 영상, 앱 발행본을 확인합니다.</li><li>이번 주 주보와 예정 행사, 변경된 장소·시간을 확인합니다.</li><li>앱에서 실제 반영 결과를 확인한 뒤 안내합니다.</li></ol><p className="mt-4 text-sm text-text-secondary">설정 활성화는 실제 연결이나 발행 성공을 의미하지 않습니다. 실제 콘텐츠 확인은 각 관리 화면에서 진행합니다.</p></section>
    <section aria-labelledby="channel-title"><h2 id="channel-title" className="mb-4 text-xl font-bold">채널별 공개 준비</h2><div className="grid gap-4 md:grid-cols-2">{channels.map(channel => <article key={channel.key} className="flex flex-col gap-3 rounded-2xl border border-border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-bold">{channel.label}</h3><span className="rounded-full bg-primary-50 px-3 py-1 text-sm font-bold text-primary-700">{channel.enabled ? '설정 활성 · 반영 확인 필요' : '앱 공개 꺼짐'}</span></div><p className="flex-1 text-text-secondary">{channel.note}</p>{preview ? <p className="text-sm text-text-secondary">체험 화면 · 실제 관리 기능은 관리자 로그인 후 이용합니다.</p> : <Button variant="secondary" asChild><Link href={channel.href}>{channel.label} 관리</Link></Button>}</article>)}</div></section>
    <section className="grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-border bg-white p-6"><h2 className="text-lg font-bold">회원 기능 연결 준비</h2><p className="mt-3 text-text-secondary">가입·복구, 상담·심방 접수, 알림 발송은 운영 연결 전입니다. 담당자 열람 범위·동의 문구·보관 기준을 확정한 후 연결합니다.</p></article><article className="rounded-2xl border border-border bg-white p-6"><h2 className="text-lg font-bold">개인 기록 보호</h2><p className="mt-3 text-text-secondary">개인 묵상·기도는 관리자 조회·검색·내보내기 대상이 아닙니다. 앱 가입은 교회 등록 성도 확인과 별개입니다.</p></article></section>
  </div>;
}
