import "server-only";
import { getPrisma } from "@daegwang/database/prisma";
import { hasDatabaseConfig } from "@daegwang/config/env";
export type DashboardSummary = { latestSunday: string; latestFirstHour: string; latestBulletin: string; nextEvent: string; published: number; drafts: number; totalMedia: number };
export async function getDashboardSummary(): Promise<DashboardSummary> { const fallback = { latestSunday: "등록된 콘텐츠 없음", latestFirstHour: "등록된 콘텐츠 없음", latestBulletin: "등록된 주보 없음", nextEvent: "예정된 일정 없음", published: 0, drafts: 0, totalMedia: 0 }; if (!hasDatabaseConfig()) return fallback; try { const prisma = getPrisma(); const [sunday, firstHour, bulletin, event, publishedCounts, draftCounts, totalMedia] = await Promise.all([
    prisma.worshipContent.findFirst({ where: { type: "SUNDAY_MORNING", deletedAt: null }, orderBy: { contentDate: "desc" }, select: { title: true } }),
    prisma.worshipContent.findFirst({ where: { type: "FIRST_HOUR", deletedAt: null }, orderBy: { contentDate: "desc" }, select: { title: true } }),
    prisma.bulletin.findFirst({ where: { deletedAt: null }, orderBy: { worshipDate: "desc" }, select: { title: true } }),
    prisma.event.findFirst({ where: { deletedAt: null, startsAt: { gte: new Date() } }, orderBy: { startsAt: "asc" }, select: { title: true, startsAt: true } }),
    Promise.all([prisma.worshipContent.count({ where: { deletedAt: null, status: "PUBLISHED" } }), prisma.notice.count({ where: { deletedAt: null, status: "PUBLISHED" } }), prisma.bulletin.count({ where: { deletedAt: null, status: "PUBLISHED" } }), prisma.event.count({ where: { deletedAt: null, status: "PUBLISHED" } }), prisma.album.count({ where: { deletedAt: null, status: "PUBLISHED" } }), prisma.ministry.count({ where: { deletedAt: null, status: "PUBLISHED" } })]),
    Promise.all([prisma.worshipContent.count({ where: { deletedAt: null, status: "DRAFT" } }), prisma.notice.count({ where: { deletedAt: null, status: "DRAFT" } }), prisma.bulletin.count({ where: { deletedAt: null, status: "DRAFT" } }), prisma.event.count({ where: { deletedAt: null, status: "DRAFT" } }), prisma.album.count({ where: { deletedAt: null, status: "DRAFT" } }), prisma.ministry.count({ where: { deletedAt: null, status: "DRAFT" } })]),
    prisma.media.count({ where: { deletedAt: null } }),
  ]); const eventDate = event ? new Intl.DateTimeFormat("ko-KR", { month: "short", day: "numeric" }).format(event.startsAt) : ""; return { latestSunday: sunday?.title || fallback.latestSunday, latestFirstHour: firstHour?.title || fallback.latestFirstHour, latestBulletin: bulletin?.title || fallback.latestBulletin, nextEvent: event ? `${eventDate} · ${event.title}` : fallback.nextEvent, published: publishedCounts.reduce((a, b) => a + b, 0), drafts: draftCounts.reduce((a, b) => a + b, 0), totalMedia }; } catch (error) { console.error("Failed to load dashboard", error); return fallback; } }
