import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const output = process.env.MOBILE_SCREENSHOT_DIR || 'test-results';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('console', (message) => { if (message.text().includes('Unexpected text node')) errors.push(message.text()); });
  const item = { id: 'example-1', version: 1, type: 'FIRST_HOUR', title: '내 안에 거하라', contentDate: '2026-10-02',
    youtube: { videoId: 'T0000000001', url: 'https://www.youtube.com/watch?v=T0000000001', thumbnailUrl: null },
    preacher: null, sermonTitle: null, scriptureReference: '요한복음 15:1–8', description: '말씀을 들으며 마음에 남은 내용을 돌아보세요.', summary: null };
  let mode = 'normal';
  let noticeMode = 'normal';
  const notice = { id: 'notice-1', title: '주요 공지', category: '교회 안내', isPinned: true, isImportant: false,
    publishedAt: '2026-10-04T00:00:00.000Z', updatedAt: '2026-10-04T00:00:00.000Z', attachmentCount: 1,
    body: '공지 본문 테스트입니다.\n두 번째 줄의 내용입니다.', attachments: [{ id: 'file-1', name: '안내.pdf', mimeType: 'application/pdf', sizeBytes: 2048, url: 'https://example.com/notice.pdf' }] };
  await page.route('**/api/v1/notices**', async route => {
    const url = new URL(route.request().url());
    const detail = url.pathname.endsWith('/notice-1');
    const headers = { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' };
    if (noticeMode === 'error' || (noticeMode === 'hidden' && detail)) return route.fulfill({ status: noticeMode === 'error' ? 503 : 404, headers, body: '{}' });
    const second = url.searchParams.get('page') === '1';
    return route.fulfill({ status: 200, headers, body: JSON.stringify(detail ? { data: notice } : { data: noticeMode === 'empty' ? [] : [{ ...notice, title: second ? '지난 공지' : notice.title }], nextPage: second || noticeMode === 'empty' ? null : 1 }) });
  });
  await page.route('**/api/v1/worship**', async (route) => {
    const url = new URL(route.request().url());
    const isDetail = url.pathname.endsWith('/example-1');
    const headers = { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' };
    if (mode === 'error') return route.fulfill({ status: 503, headers, body: '{}' });
    if (mode === 'hidden' && isDetail) return route.fulfill({ status: 404, headers, body: '{}' });
    const data = isDetail ? { data: item } : { data: mode === 'empty' || url.searchParams.get('month') === '2025-01' ? [] : [item], nextCursor: null };
    await route.fulfill({ status: 200, headers, body: JSON.stringify(data) });
  });
  await page.route('https://www.youtube.com/embed/**', (route) => route.fulfill({ contentType: 'text/html; charset=utf-8', body: '<meta charset="utf-8"><body style="background:#142e32;color:white;text-align:center;padding-top:65px;font-family:sans-serif">▶ YouTube · 테스트 영상 영역</body>' }));
  await page.goto('http://localhost:8088');
  await page.getByRole('heading', { name: '대한예수교장로회 대광교회', exact: true }).waitFor();
  await page.getByText('내 안에 거하라', { exact: false }).waitFor();
  await page.screenshot({ path: `${output}/mobile-home.png` });
  for (const title of ['말씀', '소식', '교회', 'MY']) {
    await page.getByRole('tab', { name: `${title} 탭`, exact: true }).click();
    await page.getByRole('heading', { name: title, exact: true }).waitFor();
  }
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await page.getByText('신앙생활 기록을 이어가세요', { exact: true }).waitFor();
  await page.getByRole('button', { name: '뒤로', exact: true }).click();
  await page.getByRole('button', { name: '첫시간 주님께 먼저 보기', exact: true }).click();
  await page.getByRole('button', { name: '2026-10-02 내 안에 거하라 상세 보기' }).waitFor();
  await page.screenshot({ path: `${output}/mobile-devotional-list.png` });
  await page.getByRole('button', { name: '2026-10-02 내 안에 거하라 상세 보기' }).click();
  await page.getByText('본문 위치', { exact: true }).waitFor();
  await page.frameLocator('iframe').getByText('▶ YouTube · 테스트 영상 영역').waitFor();
  await page.screenshot({ path: `${output}/mobile-devotional-detail.png` });
  assert.ok(await page.getByRole('button', { name: 'YouTube에서 보기 ›' }).isVisible());
  mode = 'hidden'; await page.reload();
  await page.getByText('현재 공개되지 않은 말씀입니다.').waitFor();
  mode = 'normal'; await page.getByRole('button', { name: '목록으로', exact: true }).click();
  await page.getByRole('button', { name: /날짜 선택/ }).click();
  await page.getByLabel('조회 연월').fill('2025-01');
  await page.getByRole('button', { name: '적용', exact: true }).click();
  await page.getByText('등록된 묵상이 없습니다').waitFor();
  mode = 'error'; await page.reload();
  await page.getByText('말씀을 불러올 수 없습니다. 잠시 후 다시 시도해 주세요.').waitFor();
  mode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).click();
  await page.getByRole('button', { name: '2026-10-02 내 안에 거하라 상세 보기' }).waitFor();
  mode = 'empty'; await page.goto('http://localhost:8088');
  await page.getByText('공개된 묵상이 아직 없습니다.', { exact: true }).waitFor();
  mode = 'error'; await page.reload();
  await page.getByText('말씀을 불러올 수 없습니다. 잠시 후 다시 시도해 주세요.', { exact: true }).waitFor();
  mode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).click();
  await page.getByText('내 안에 거하라', { exact: false }).waitFor();
  await page.getByRole('tab', { name: '소식 탭', exact: true }).click();
  await page.getByRole('button', { name: '공지사항', exact: true }).click();
  await page.getByRole('button', { name: '주요 공지', exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-notices.png` });
  await page.getByRole('button', { name: '다음 공지', exact: true }).click();
  await page.getByRole('button', { name: '지난 공지', exact: true }).waitFor();
  await page.getByRole('button', { name: '이전 공지', exact: true }).click();
  await page.getByRole('button', { name: '주요 공지', exact: true }).click();
  await page.getByText('두 번째 줄의 내용입니다.', { exact: false }).waitFor();
  await page.getByRole('button', { name: '안내.pdf', exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-notice-detail.png` });
  noticeMode = 'hidden'; await page.reload();
  await page.getByText('현재 공개되지 않은 공지입니다.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '안내.pdf', exact: true }).count(), 0);
  noticeMode = 'empty'; await page.getByRole('button', { name: '공지 목록', exact: true }).click();
  await page.getByText('등록된 공지가 없습니다', { exact: true }).waitFor();
  noticeMode = 'error'; await page.reload();
  await page.getByText('공지를 불러오지 못했습니다. 다시 시도해 주세요.', { exact: true }).waitFor();
  noticeMode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).click();
  await page.getByRole('button', { name: '주요 공지', exact: true }).waitFor();
  let bulletinMode = 'normal';
  const bulletin = { id: 'b1', title: '테스트 주보', worshipDate: '2026-10-04T00:00:00.000Z', summary: '주보 미리보기 테스트', pdf: { name: 'sample.pdf', sizeBytes: 1024, url: 'https://example.com/sample.pdf' } };
  await page.route('https://example.com/sample.pdf', route => route.fulfill({ contentType: 'text/html', body: '<p>Test document viewer</p>' }));
  await page.route('**/api/v1/bulletins**', route => {
    const url = new URL(route.request().url());
    const detail = url.pathname.endsWith('/b1');
    const headers = { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' };
    if (bulletinMode === 'error' || (bulletinMode === 'hidden' && detail)) return route.fulfill({ status: bulletinMode === 'error' ? 503 : 404, headers, body: '{}' });
    return route.fulfill({ headers, body: JSON.stringify(detail ? { data: bulletin } : { data: url.searchParams.get('month') === '2025-01' ? [] : [bulletin], nextPage: null }) });
  });
  await page.goto('http://localhost:8088/news');
  await page.getByRole('button', { name: '주보', exact: true }).click();
  await page.getByRole('button', { name: '테스트 주보', exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-bulletins.png` });
  await page.getByRole('button', { name: '테스트 주보', exact: true }).click();
  await page.frameLocator('iframe[title="주보 문서"]').getByText('Test document viewer').waitFor();
  await page.getByRole('button', { name: '원본 열기', exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-bulletin-detail.png` });
  bulletinMode = 'hidden'; await page.reload();
  await page.getByText('현재 공개되지 않은 주보입니다.', { exact: true }).waitFor();
  assert.equal(await page.locator('iframe').count(), 0);
  bulletinMode = 'normal'; await page.getByRole('button', { name: '주보 목록', exact: true }).click();
  await page.getByRole('button', { name: '주보 연월 선택', exact: true }).click();
  await page.getByLabel('주보 조회 연월').fill('2025-01');
  await page.getByRole('button', { name: '적용', exact: true }).click();
  await page.getByText('등록된 주보가 없습니다', { exact: true }).waitFor();
  bulletinMode = 'error'; await page.reload();
  await page.getByText('주보를 불러오지 못했습니다. 다시 시도해 주세요.', { exact: true }).waitFor();
  bulletinMode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).click();
  await page.getByRole('button', { name: '테스트 주보', exact: true }).waitFor();
  let eventMode = 'normal';
  const event = { id: 'e1', title: '테스트 교회 행사', category: '모임', startsAt: '2026-10-11T01:00:00.000Z', endsAt: '2026-10-11T03:00:00.000Z', isAllDay: false, location: '테스트 장소', ministryName: null, description: '행사 안내 테스트입니다.' };
  await page.route('**/api/v1/events**', route => {
    const url = new URL(route.request().url());
    const detail = url.pathname.endsWith('/e1');
    const headers = { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' };
    if (eventMode === 'error' || (eventMode === 'hidden' && detail)) return route.fulfill({ status: eventMode === 'error' ? 503 : 404, headers, body: '{}' });
    return route.fulfill({ headers, body: JSON.stringify(detail ? { data: event } : { data: eventMode === 'empty' ? [] : [{ ...event, title: url.searchParams.get('period') === 'past' ? '지난 테스트 행사' : event.title }], nextPage: url.searchParams.get('page') === '0' ? 1 : null }) });
  });
  await page.goto('http://localhost:8088/news');
  await page.getByRole('button', { name: '교회 행사', exact: true }).click();
  await page.getByRole('button', { name: '테스트 교회 행사', exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-events.png` });
  await page.getByRole('button', { name: '다음 행사', exact: true }).click();
  await page.getByRole('button', { name: '이전 행사', exact: true }).waitFor();
  await page.getByRole('tab', { name: '지난 행사', exact: true }).click();
  await page.getByRole('button', { name: '지난 테스트 행사', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '이전 행사', exact: true }).count(), 0);
  await page.getByRole('tab', { name: '예정', exact: true }).click();
  await page.getByRole('button', { name: '테스트 교회 행사', exact: true }).click();
  await page.getByText('행사 안내 테스트입니다.', { exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-event-detail.png` });
  await page.getByRole('button', { name: '내 일정에 추가', exact: true }).click();
  await page.getByText('신앙생활 기록을 이어가세요', { exact: true }).waitFor();
  await page.getByRole('button', { name: '뒤로', exact: true }).click();
  eventMode = 'hidden'; await page.reload();
  await page.getByText('현재 공개되지 않은 행사입니다.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '내 일정에 추가', exact: true }).count(), 0);
  eventMode = 'empty'; await page.getByRole('button', { name: '행사 목록', exact: true }).click();
  await page.getByText('등록된 행사가 없습니다', { exact: true }).waitFor();
  eventMode = 'error'; await page.reload();
  await page.getByText('행사를 불러오지 못했습니다. 다시 시도해 주세요.', { exact: true }).waitFor();
  eventMode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).click();
  await page.getByRole('button', { name: '테스트 교회 행사', exact: true }).waitFor();
  let churchMode = 'normal';
  const contact = { siteName: '테스트 교회', address: '테스트 주소', addressDetail: '테스트 상세', phone: '02-1234-5678', email: 'hello@example.com', websiteUrl: 'https://example.com', latitude: null, longitude: null, transitInfo: '테스트 교통 안내', parkingInfo: '테스트 주차 안내' };
  await page.addInitScript(() => { window.__openedLinks = []; window.open = url => { window.__openedLinks.push(String(url)); return null; }; });
  await page.route('**/api/v1/church/**', route => {
    const about = route.request().url().endsWith('/about');
    const headers = { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' };
    if (churchMode === 'error' || churchMode === 'hidden') return route.fulfill({ status: churchMode === 'hidden' ? 404 : 503, headers, body: '{}' });
    const section = new URL(route.request().url()).pathname.split('/').at(-1);
    const extra = {
      pastor: { name: '테스트 목회자', position: '담임목사', introduction: '테스트 인사말', quote: null, career: ['테스트 약력'], imageUrl: null },
      newcomer: { title: '새가족', content: { heroTitle: '테스트 환영 안내', heroDescription: '환영합니다', applicationInfo: '테스트 안내 절차' } },
      contact: churchMode === 'empty' ? { ...contact, address: '', addressDetail: '', phone: '', email: '', websiteUrl: null } : contact,
    };
    if (section in extra) return route.fulfill({ headers, body: JSON.stringify({ data: extra[section] }) });
    return route.fulfill({ headers, body: JSON.stringify({ data: about ? { title: '테스트 교회 소개', content: { body: '교회 소개 본문 테스트' } } : churchMode === 'empty' ? [] : [{ id: 's1', name: '테스트 주일예배', dayLabel: '주일', timeLabel: '오전 11시', location: '테스트 예배당', note: '테스트 안내' }] }) });
  });
  await page.goto('http://localhost:8088/church');
  await page.getByRole('button', { name: '교회소개', exact: true }).click();
  await page.getByText('교회 소개 본문 테스트', { exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-church-about.png` });
  churchMode = 'hidden'; await page.reload();
  await page.getByText('현재 공개된 안내가 없습니다.', { exact: true }).waitFor();
  assert.equal(await page.getByText('교회 소개 본문 테스트', { exact: true }).count(), 0);
  churchMode = 'normal'; await page.getByRole('button', { name: '예배안내', exact: true }).click();
  await page.getByText('테스트 주일예배', { exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-church-schedules.png` });
  churchMode = 'empty'; await page.reload();
  await page.getByText('등록된 예배 안내가 없습니다', { exact: true }).waitFor();
  churchMode = 'error'; await page.reload();
  await page.getByText('교회 안내를 불러오지 못했습니다. 다시 시도해 주세요.', { exact: true }).waitFor();
  churchMode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).click();
  await page.getByText('테스트 주일예배', { exact: true }).waitFor();
  await page.goto('http://localhost:8088/church');
  await page.getByRole('button', { name: '담임목사', exact: true }).click();
  await page.getByText('테스트 목회자 · 담임목사', { exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-church-pastor.png` });
  churchMode = 'hidden'; await page.reload();
  await page.getByText('현재 공개된 안내가 없습니다.', { exact: true }).waitFor();
  assert.equal(await page.getByText('테스트 목회자 · 담임목사', { exact: true }).count(), 0);
  churchMode = 'normal'; await page.goto('http://localhost:8088/church');
  await page.getByRole('button', { name: '새가족안내', exact: true }).click();
  await page.getByText('테스트 환영 안내', { exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-church-newcomer.png` });
  await page.getByRole('button', { name: '3. 문의하기', exact: true }).click();
  await page.getByText(contact.phone, { exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-church-contact.png` });
  assert.equal(await page.getByRole('button', { name: '전화하기', exact: true }).isEnabled(), true);
  await page.getByRole('button', { name: '이메일', exact: true }).click();
  await page.getByRole('button', { name: '교회 홈페이지', exact: true }).click();
  assert.deepEqual(await page.evaluate(() => window.__openedLinks), ['mailto:hello%40example.com', 'https://example.com/']);
  churchMode = 'empty'; await page.reload();
  assert.equal(await page.getByRole('button', { name: '전화하기', exact: true }).isDisabled(), true);
  churchMode = 'normal'; await page.goto('http://localhost:8088/church-info/location');
  await page.getByText('테스트 교통 안내', { exact: false }).waitFor();
  await page.screenshot({ path: `${output}/mobile-church-location.png` });
  await page.getByRole('button', { name: '지도 앱에서 길찾기', exact: true }).click();
  assert.equal(new URL((await page.evaluate(() => window.__openedLinks))[0]).searchParams.get('destination'), contact.address);
  churchMode = 'empty'; await page.reload();
  await page.getByText('등록된 위치 정보가 없습니다.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '지도 앱에서 길찾기', exact: true }).isDisabled(), true);
  churchMode = 'error'; await page.reload();
  await page.getByText('교회 안내를 불러오지 못했습니다. 다시 시도해 주세요.', { exact: true }).waitFor();
  churchMode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).click();
  await page.getByText('테스트 교통 안내', { exact: false }).waitFor();
  let searchMode = 'normal';
  const sermon = { ...item, id: 'sermon-1', type: 'SUNDAY_MORNING', title: '함께 듣는 주일 말씀', preacher: '테스트 설교자' };
  await page.route('**/api/v1/worship**', route => {
    const url = new URL(route.request().url()); const detail = url.pathname.endsWith('/sermon-1');
    const headers = { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' };
    if (searchMode === 'error' || (searchMode === 'hidden' && detail)) return route.fulfill({ status: searchMode === 'hidden' ? 404 : 503, headers, body: '{}' });
    const rows = url.searchParams.get('q') === '없는검색어' ? [] : url.searchParams.get('group') === 'special' ? [{ ...sermon, id: 'special-1', title: '특별 말씀 테스트', type: 'SPECIAL' }] : [sermon];
    return route.fulfill({ headers, body: JSON.stringify(detail ? { data: sermon } : { data: rows, nextCursor: null }) });
  });
  await page.goto('http://localhost:8088/worship');
  await page.getByRole('button', { name: '주일설교 · 특별말씀', exact: true }).click();
  await page.getByRole('button', { name: sermon.title, exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-sermons.png` });
  await page.getByRole('tab', { name: '특별말씀', exact: true }).click();
  await page.getByRole('button', { name: '특별 말씀 테스트', exact: true }).waitFor();
  await page.getByRole('tab', { name: '주일설교', exact: true }).click();
  await page.getByRole('button', { name: sermon.title, exact: true }).click();
  await page.getByText('설교 소개', { exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-sermon-detail.png` });
  searchMode = 'hidden'; await page.reload(); await page.getByText('현재 공개되지 않은 말씀입니다.', { exact: true }).waitFor();
  searchMode = 'normal'; await page.goto('http://localhost:8088/worship-search');
  await page.getByLabel('말씀 검색어').fill('요한복음'); await page.getByRole('button', { name: '검색', exact: true }).click();
  await page.getByRole('button', { name: sermon.title, exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-worship-search.png` });
  await page.getByRole('button', { name: '상세 필터', exact: true }).click();
  await page.getByLabel('시작일', { exact: true }).fill('2026-11-01'); await page.getByLabel('종료일', { exact: true }).fill('2026-10-01');
  await page.getByRole('button', { name: '결과 보기', exact: true }).click();
  await page.getByText('날짜는 YYYY-MM-DD 형식으로, 시작일은 종료일 이전으로 입력해 주세요.', { exact: true }).waitFor();
  await page.getByRole('button', { name: '필터 초기화', exact: true }).press('Enter');
  assert.equal(await page.getByLabel('시작일', { exact: true }).inputValue(), '');
  await page.getByRole('button', { name: '결과 보기', exact: true }).press('Enter');
  await page.getByRole('heading', { name: '말씀 필터', exact: true }).waitFor({ state: 'hidden' });
  await page.getByLabel('말씀 검색어').fill('없는검색어'); await page.getByRole('button', { name: '검색', exact: true }).click();
  await page.getByText('검색 결과가 없습니다', { exact: true }).waitFor();
  searchMode = 'error'; await page.getByLabel('말씀 검색어').fill('기도'); await page.getByRole('button', { name: '검색', exact: true }).click();
  await page.getByText('말씀을 불러올 수 없습니다. 잠시 후 다시 시도해 주세요.', { exact: true }).waitFor();
  searchMode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).click(); await page.getByRole('button', { name: sermon.title, exact: true }).waitFor();
  eventMode = 'normal';
  await page.goto('http://localhost:8088/church-calendar');
  await page.getByRole('button', { name: /^2026-10-11 일정/ }).click();
  await page.getByRole('button', { name: '테스트 교회 행사', exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-church-calendar.png` });
  await page.getByRole('button', { name: '다음 달', exact: true }).click();
  await page.getByRole('button', { name: '오늘로 이동', exact: true }).click();
  await page.getByRole('button', { name: /^2026-10-11 일정/ }).click();
  await page.getByRole('button', { name: '테스트 교회 행사', exact: true }).click();
  await page.getByText('행사 안내 테스트입니다.', { exact: true }).waitFor();
  let prayerMode = 'normal';
  const prayer = { ...notice, id: 'prayer-1', title: '테스트 공동기도', category: '공동기도', body: '함께 드리는 기도 테스트입니다.', attachmentCount: 0, attachments: [] };
  await page.route('**/api/v1/prayers**', async route => {
    const url = new URL(route.request().url()); const detail = url.pathname.endsWith('/prayer-1');
    await route.fulfill({ status: prayerMode === 'error' ? 503 : prayerMode === 'hidden' && detail ? 404 : 200, contentType: 'application/json', headers: { 'Access-Control-Allow-Origin': '*' }, body: JSON.stringify(detail ? { data: prayer } : { data: prayerMode === 'empty' ? [] : [prayer], nextPage: null }) });
  });
  await page.goto('http://localhost:8088/news'); await page.getByRole('button', { name: '교회 공동기도', exact: true }).press('Enter');
  await page.getByRole('button', { name: prayer.title, exact: true }).press('Enter');
  await page.getByText(prayer.body, { exact: true }).waitFor();
  await page.screenshot({ path: `${output}/mobile-common-prayer.png` });
  await page.getByRole('button', { name: '나의 기도로 기록하기', exact: true }).press('Enter');
  await page.getByRole('button', { name: '로그인', exact: true }).waitFor();
  prayerMode = 'hidden'; await page.goto('http://localhost:8088/prayers/prayer-1');
  await page.getByText('현재 공개되지 않은 공동기도입니다.', { exact: true }).waitFor();
  prayerMode = 'empty'; await page.goto('http://localhost:8088/prayers'); await page.getByText('등록된 공동기도가 없습니다', { exact: true }).waitFor();
  prayerMode = 'error'; await page.reload(); await page.getByRole('button', { name: '다시 시도', exact: true }).waitFor();
  prayerMode = 'normal'; await page.getByRole('button', { name: '다시 시도', exact: true }).press('Enter'); await page.getByRole('button', { name: prayer.title, exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: home, tabs, guest login, devotional, notices, bulletins, events, church details, sermon search/filters, church calendar, common prayer list/detail/hidden/empty/error recovery and private action login gate; 390px screenshots. API/video content is a test fixture.');
} finally { await browser.close(); }
